apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 4m
      limit: 3
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/Creaty-Co/creaty-chart
      targetRevision: {{ .Values.stage.chartVersion }}
      path: .
      helm:
        valueFiles:
          - $values/values/environments/global.yaml
          - $values/values/environments/stage.yaml
        parameters:
          - name: version
            value: {{ .Values.environments.stage.version }}
    - ref: values
      repoURL: https://github.com/Creaty-Co/creaty-root-chart
      targetRevision: {{ .Values.stage.chartVersion }}
