api:
  resources:
    limits:
      memory: 500Mi

redis:
  storage:
    volumes:
      data:
        enabled: false

postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.postgres.main }}'

cal_postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.cal_postgres.main }}'
