secrets:
  Opaque:
    api-secrets:
      SECRET_KEY: AgCVvvhActq4EhaMILEZrzBHzi4OO9zUBSbjwr7sNB2rGGQIC5ZWAcm/CsEJ4PM+WhHAsKeMccf5Dzod/fKNmBpJGls7A9MHfkRnWwnkQmgRMjeUjmnvkS7VdJ8yIHppKYKIFJiOxqKxgUP53b2Vouqrlr4qMGWP7SRcIkfVXRhKiaekj2Y/EQCXEV+W+Zp9tBn9IbxB/O4BHZAZnY5AfG7/AeugiSyM2KJ61pz/N0aCsStipEE7m0JFrIZejjEKg7FZxUlRJ3Qf8ClInnG1HhIlYraTmrYwaeqx0icQaUXoCMTjHFNJPCxEjPIw0CTD8Tqay551qSkIFrflntBy+VpAuHrNuhQ8Z+FrOBguOS1X+xux0xuw1/7hWuBrOv/fuwsZvLPerjrA77+3l8EDvrGao/oVsC5cG2FnZPDUaD5gcbiJ/nC+qUyenwylwnGNZE6Lobo9p1qv6StKsUgKh/5jdqi5KCwzyY1VH9rTV1Li58ZG24IFv03JMaZo7+hCqkQZdFJY/xfgIsFLV9wy7nTm/GlKFZozSA7VURUeOtuN9LXxpH5+x5V4/pxkWK7Za170bMY8VUTGe6bZXk/D0Y0Qd8jZ+cRV1cCVWGDisOk/eb5Bjr2UoVgsycK0vr7CC7peEUK2MiMK1aj2nDTSfCp/1ANyXKGDJyymeRjbiuhQtFpnQ8E6WT4ORHLAsPinEdU27A7dHA==
    postgres-secrets:
      POSTGRES_PASSWORD: AgCaa+XiU4PMwk+zv0Ag/zaKS/7xBRATYKEcCMXIE49uj62jm1C3NLnKcgnIi+ldp8KxDTel+j5uIYHMAEUGzKgdxeEcCL6jgsXKk22wvUEjNaTkJfvI5oZGx0rWAXrxJTGrr9+pujRAWpJYWd2Ga7UMscIsLNsvYm6NmLznQNam8rq2qabnwbHgYXYqZRoZvi47HTJSibMeelEQf2sl4glZTum/mU35Q+CdymFWCtt1UbqFmnlIIazzVdsXZr6pZyPqmo5KVpFhGIIz7e+32GlNHyvxTlkkdfmeRZXGdVrWjuNA96CiKFE4guk3DOA98t/z7zjdCfiovg/qx7pquXf5B2L0K9O4aNKREit1ZWDJUFSFZZnGpsU4o8Cjl5xhGaqb6FqxGJU28wzgmFF4GVyI5VsozL0bGIcHOhReurAcMNT84xTP18o6qopy3W25uknSI51JQVARJhlCadg92UCLKVQiJ2SwUyeKpa5Cw932yyhS+hH0k8RFezEo9SJ3O8O3w8HoM2wuSa5w4awrZSSin8wr/7B612G/nK7k/6kog3K0cIB1L2go/cGgAujmCKdDpTT8PL5M5BHNq7Gl+OzB6qHirV3B0QtneXYjQp1oXw99rvCCtw6/57ghRiTh99NLRxu64Wb+93sKNHk/T0ZjtGF1iM8G2ZPtlyUx5PC1KoGaohlFbRwBw7aHDZPsUVGJK1AvvtQ=
    cal-postgres-secrets:
      POSTGRES_PASSWORD: AgATfBvQi+F49mNWxklh3/TE23PXD7dqlILBflSSkpiMGq83ys28m91krn3eIZLNZkWC5uD64dkUZOCPcDfpYKiUKOTUaQ86DeR64Xkr22Hrd5vE60o8nQiV599aDNtEQoDWUOzANmf9Qb4MQERaw0W1DBhnIYjBlXMitLLkGbammHwPiOTdPqq5X5byii6FJtfs8OC2VpEqbLJ0laonQ3vztQ20I1agE0ITJIwQ1ZQmzHIvMzdb/WdN+sXCYX/bY6day4df93lNS5q+jYBg//X6Ij2v31+R+cK3g9+LvqOF2XtGWtAUys0Zdd2rt6WmaZP31rZMbeD9i7Kzjw/VXNx1oAc6naLRUKqnhjp40h+Uu9yZB3lLTSO2X2i478K8dLnSRHsAAICaPG/c5NW3lrX8JM5VIdHmXIk9MOytNWs2rkt5J3hWLm1RCeHe31oxZr/eEVEGv74rwzhx35wL0KrCiPqHXOv65NQO0OL9CupmXiTmAEB/pktcbpH83QOg1YnEH783nqUf1VNuUw/qkESZeDIC9pQODUI2XH/uuW0X5gAeMICRH4uaG2TuegFKg4bsJnnL28U5qIxEi0GSJrHAZR/po7IOrf/qJyORFDmEAvi31qrDLG7pcJRzJosW3qYpGi3MTXF3BIyHxaRMXnaMui3w4KU/2sSqPQewYzSzVlchi8lJ8eVu/6mWZAGcMYGrfnxJRPY=

api:
  resources:
    limits:
      memory: 500Mi

postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.postgres.main }}'

cal_postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.cal_postgres.main }}'
