api_version: e485757dc864a7d4f79ccca449974d9d8516f6c9
web_version: v2.12.0

secrets:
  Opaque:
    api-secrets:
      SECRET_KEY: AgCod04tUWbjuXsoJFKTBNRQAEAulykeLP9zahn2sTfc0oIVfZEuHmMvtaGcryRxEUtLqlNhS1f/AC9kkOgWqci9cMuwa0ryYk1xcHPammzdmuFh1NK07JZCudmA2vX+q358KJqTB0zB0+MkhBd7SEWhINTJveBZbgNMGTH4mJzIZcBxLduGrrPvVJlL4u6wW8yGRCfjdAyKM9q86Ew6DcxngKNy8wTDp6Pfrte1ZTky3opIWOPPsTZjoEiArX1yxv2jHm/dMV9pNAPl7ZJeWj6Qj1UIEdRr1Xq6KXpA6eJPrDq1+a6ExAd2acWNskh4X1EphwOOyNTewdNssongalhkCFMqh7LMa5NM3xYpUhihsXmE1LgygL6w8NDI9/13PI/Uv2sj/Bch9h4uIIZCRU4e4SAj1eqzPkXofcJwvNFsxHEq6oYcjGNHUHN9yhec7ICzHmrH0nghbGZdkL9cdK15EvAPC0FZCmva69uoq0+VowGDTwawiEHKwCHV5TZJduFwD7Tb0IF/ii9mP6ERm9CDvvQAjJdgJVrZmZyX3qHDjG260QUPp2H++SpmtQ0dyTFfdA5/sLcJlp/XkIF9z6gFKmR7jRym8tWmpWrj74IDm8k5HCVQylTvFhPykh8io98vq99VMZUCOqDo/r+mfUwFBrmFzrTDXKBwyCITi4G4cpkjO5A+/b+v3xJozGtQDvdh8uHMSCs=
    postgres-secrets:
      POSTGRES_PASSWORD: AgBauDtVTPSRTrS7OPPCVgu802q+L9XuJlIh9DIKyiU2nPN2NqmysaOyJ8J0Th6H/7AoKoT88e+JShDDQwQIBDKJu1mXYUqaqnree/lM6wQ1LT5XaBtN9lxXZ466tiKyHs8buwjIFohD22sx2TqOW0b3nyoFiX4BR+hLYh8aBOxT8l4mZ6gM0U/8heSYMcrkTiAh4EyiINnnDWOaBDYFbpSsnEEGZnAFHRtMowsFAqwAQVPbWseqVxcLgYreMcrEUju4GSH/keOJeQkaItyQ3gYIw9hvVDomUkeaVI44YG0oTnLgTbeNdVZkfw/iByKegNCkLsOHgcGzgmwnhW0e2GzNXdiXfnk9QPZOzRH4UHxLP7CmEI8PVK2rgyOMLlj6eF3vSzpl43TaO9HMcr5u3ZVkwUOWh7pEaqbwnhaLhh0zjf6yFzjUWaFmG8hY7ohPDHlliOJy76ZAk/YZgpUuP8LHBdjmASxWG8XNKH0ZQCf40f27OO0eWolPtLSkD+6XXDXv3mMbr5d4LSTPOE91biNGCo17faPVKCA4Jhx4pUYrqybnF5rUWqRhklh9NYKsiYPf5dukzYkcJnukZztIFNY/fE+W6E9PzmlGX9TzlFCYc/S2vYBQzEho1kq/N0YSiDTw0Oh/IlIbWn2btc0K+yBl6hJzco4InCUS7GsEFWXv1LVe+TsGqYG53FL5WPPLStUfYp1Ii3TD
    cal-postgres-secrets:
      POSTGRES_PASSWORD: AgBOMpb6lPJV4lGwzyyFp4P1a64/BaGd1AaFeUJ4EPxfK3lDYq1HfRilzr4wrm3v6BXBoE/H6nfcu72vrK73GdAzkyU8s781kzPL0ZnUiEshB7ZkcMOnFD9arLugxXic1Z79hJtNSYb84ujFz9DNs3t3yI5Odt2zmPeAdi8v+Yz+QTVkEmG9atS+HReHYKwHnYCnTlab1tU5L3aFz5S1WjYZdTtNJ1Mltfgy+z32V/6jKarT8aldjDA3qUfSC9mut5FBJUR5GFbJrNKkdgq0mRPhwR8PHAURuVP9VRaN88P5HE07Hx6y2w95GEA3y0vn7nsMXOU9VHu2V4md6WaF7HTOLVLVHGw6a0bvzPsRoO+2Mc7DMtTC9giMnZu7OqF6NY3txlI6fukifs0EjDNTbzvz47mdXsZmP/TSH1YOHzqWkTGwzzkn6fyHaVaz7HMQ3zILQe2q3hgnjHfQkaGooSfm2pM+o5sPfZIIWs8lWi5MLfvgJX+gSpxeiwfD+v6N1xz0zmec/9uFr9lRcydeK4LfgW5tnvPJf55p3PKT2HUbAvFIcHshRHl8m/9ssrtp40DJMkamGKgK88tVvVt8Zm6IxjtiAXebE1XwjcrXJ1minvTd81FoirEsfo+jhbAQYyDubZwYm/D8vRNQDgXhbGH0BTwc+PaGuiz00E1rqx/2gzD7SKfs5M/0gvivB9zOhO070QmDOrjG

redis:
  vars:
    maxmemory: 30mb
  resources:
    requests:
      memory: 40Mi
    limits:
      memory: 60Mi

postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.postgres.main }}'

cal_postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.dev.cal_postgres.main }}'
