api_domain: api.creaty.club
web_domain: creaty.club
cal_domain: cal.creaty.club

api:
  envs:
    DEBUG: "0"
    ANON_THROTTLE_RATE: 100/s
    USE_BROWSABLE_API: "0"
    CELERY_REDIS_MAX_CONNECTIONS: "100"
    CELERY_BROKER_POOL_LIMIT: "100"
    LOG_PRETTY: "0"
    LOG_REQUESTS: "0"

postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.prod.postgres.main }}'

platform_postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.prod.platform_postgres.main }}'
