api_domain: api.creaty.club
web_domain: creaty.club
cal_domain: cal.creaty.club

secrets:
  Opaque:
    api-secrets:
      SECRET_KEY: AgA2uDpspFqY66MPLQHPUZ5jTbTGFEQdV5cjeVTWpL29DLKx7GJk233J9I9UxYQSZxu+t1UKn+M49XfbKIjEwb7xDJe0IcQqszUptDMY1ZdVMzEf+E/fppbvUt0CDqiiUd7CJ9jRNGkbSzx7F0LFmt0DxmO9Fw0e/ipCLkmv9GMABIHBQZCPbFVQorBAUkGvi0mm6UwExiez9SFS22crMbH7dP4CyyqplHxzMG3UCG+k2IKynzCJo3Xq4Y3h37kLvRiWNtCHqloay7/nl/2QRDFEfFypgO4QvhgUJ1TsSljqae4CTcGAtiqVkcllLdHPdbE4+M7Jl3CrRuJuJJEfWJPl9LHs8G3TFEZvQao5mwOuR6GED3ms9k14OquL4hwkD+IPmyTRGTs944XOVqzpxzD9v1VMxEcUVi5Ofjxl5MdktoxBKlDBgnA7XHhbLdwthOtuMTnthbK8AjcJ7bpuVJSVM3J6wYfN9ObmqJDsLH/qCjp/2AHnt4jzMgYlwUR8nXC3ZZx5cAIoGE6mMSVB/ySi0Ytofx0sePltodfKPVU69bDZIcpmaDCGkj1PnO5L6jdlK3jas/foJdY1WE2APCXZOnMSU1kQNO7/6Ao2G5fLYVyZPVbC9aYDLdeiVHX2/6oVSiJrCCLPPkSP614iH+8sc7XRYam5JK5uOJxJpQbHWZd4cKgpcDvXnhNVDRvj08giYXQMDrSc3bWMuwgToMNL8aNeUueVX2HLrSOAmztuVg==
    postgres-secrets:
      POSTGRES_PASSWORD: AgBZuLe8gIJlIeqrqA7/qyO4vDUj2lg7YfLOqIqA541vj8bVqjfgs8RT+ZLhPz2qpuLCEIORSXmCqGTz2uExySa1k4dTIgus8RGLlHDtQ4HgRz68wxHfDtp0d2lbwbxCwR7/LBm4jDR9fzcHvwP5MKcZg2vOZkmQZTfvyknmdNOl1w7bLAzcgAfAyuGnnAZyaPruGV4YBb6YwWNI106fR4hP1uCf5TbAUyY1A1zh9fa5rkHftz5vc6o1A2VzSWvRZ5+L3U51RXi7VXQZlshXpNd18eqapEQEjrrxzSwtxtV1oe5EyXPCq61JBVlSs9BhC3Wzk/l4qdG95YNey23wB8rf7av14X4L4zDEdAYCSOs557utA0FvDDOHheNxNif0p1j/hBMIrRFiBTFkVyFjVjTZ25N4ErqOB/S2hXKZjOR4Hr1wZYuSlkdv5uAmvdLZzXoUPRlsAuYzrw+ZC4/kFXzycc9W92+DgIU/7AJdZNsadJ1noIq2LpDz5RaDLbnHYzhRq6i+KzuhCmiPPBU8D3cMEqM4tDQuSL3zRyZZyMitGgx5jKvd8K98R0QSOQCwayGlSWXlFcVvMtJf/sNeqOgh6ErgQPG3yASLlE7eIWWC3NXRprqimZCF1nzWL4GX3SLcLZGFlZ6EhqZ9cLXw/M23Xmu71ObQzVDMztr278fcWaxo/UHKZXyXlqJjB1DjTnZH4zPftKsYh7ucOUgEkkYV
    cal-postgres-secrets:
      POSTGRES_PASSWORD: AgBPVZ+tURmo9gJA/Wb65DrKl51ubbbWdQvUA0sdZ9N8aUl/lOu6pSV2MtaMDOZJtsZ8ZdQHudmOESJPSmn7C2TI2cDZ50v91PfTzJAt91oeco1bxOqaU5/2H1jTGN6iYShaONu5Opo1JCMZTZ2lS/i4GdlFY+n7XLWDanvZ4LwjXKS+LnxjQPozzXcqMQoiSaAqwfFGNac6sxgHeIVVCO3PzDAb/lnGXo4/uYbDDmo7q2/6uqWtDs2y88JH+U5vXlRr6kNKOmQxmO8YzzqP02ZxJI4OUH7MLFwUWq+BkXCgiavc2ZIAXa2ivUJQXT2C4Sa/BTx0+HjqM50R+FV6EBND1xDC49ThCVfbJSKxCmuu/4cXolAxvhrblHIjXRg6v5v/3tWbJOmhnOdgHuzZAtP3Q7qtoqAPEjkWwYWbJ4Hlo6pEUlBUzj/iqJwyJyVL4HRKZwE50a9noZejKvrm+Ry/j3/oxLgq4VN2s2MpfUCXCoAfV3ITHQQ1WunMstCzB/rS2tSyBojbS04iRWE71Tsb/QfB3ucC9beKVvAaVF8/C8fYceQp1yT4hEEgQPp1yj2AYaMzP52WBTLdVTmq0TpV+MWiMbVQFo6mZ/UrRLLB/5PND4JXH6zHcagr0pg07uEghD07TXxndNWN8o8Uj7D6OtK9hh0+vOE3RdIBUSmHDWk2P8EU2ag48KS5I8a4jyzbyXwOKPCMw3s1oD5gB/bE

api:
  envs:
    DEBUG: "0"
    ANON_THROTTLE_RATE: 100/s
    USE_BROWSABLE_API: "0"
    CELERY_REDIS_MAX_CONNECTIONS: "100"
    CELERY_BROKER_POOL_LIMIT: "100"
    LOG_PRETTY: "0"
    LOG_REQUESTS: "0"

postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.prod.postgres.main }}'

cal_postgres:
  nodePorts:
    main: '{{ .Values.global.nodePorts.prod.cal_postgres.main }}'
