apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-stack-secrets
  namespace: prometheus-stack
spec:
  encryptedData:
    {{- range $key, $value := .Values.global.secrets.prometheus_stack_secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: prometheus-stack-secrets
    type: Opaque
