apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 4m
      limit: 3
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: {{ .Values.certManager.version }}
      helm:
        valueFiles:
          - $values/values/cert-manager.yaml
    - ref: values
      repoURL: https://github.com/Creaty-Co/creaty-root-chart
      targetRevision: main
    - repoURL: https://github.com/Creaty-Co/creaty-root-chart
      targetRevision: main
      path: manifests/cert-manager
