apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 4m
      limit: 3
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=false
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: {{ .Values.vault.version }}
      helm:
        valueFiles:
          - $values/values/vault.yaml
    - ref: values
      repoURL: https://github.com/Creaty-Co/creaty-root-chart
      targetRevision: main
    - repoURL: https://github.com/Creaty-Co/creaty-root-chart
      targetRevision: main
      path: manifests/vault
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/objectSelector/matchExpressions
