name: "Dispatch: build ArgoCD images"

on:
  workflow_dispatch:
    inputs:
      avp_version:
        type: string
        required: true
        description: without "v" prefix

jobs:
  build-argocd-vault:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository to lower case
        # language="shell script"
        run: |
          repository=${{ github.repository }}
          echo "REPOSITORY=${repository,,}" >> ${GITHUB_ENV}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: images/argocd
          file: images/argocd/argocd-vault.dockerfile
          build-args: ARGOCD_VAULT_PLUGIN_VERSION=${{ inputs.avp_version }}
          push: true
          tags: ghcr.io/${{ env.REPOSITORY }}/argocd-vault:v${{ inputs.avp_version }}
